name: Issue notification - open

on:
  issues:
    types: [opened]

jobs:
  notify:
    name: Notify about issue changes
    runs-on: ubuntu-latest
    steps:
      - name: Send TG message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "rmrk-tools **new** [issue #${{ github.event.issue.number }}](https://github.com/swader/rmrk-tools/issues/${{ github.event.issue.number }}): ${{ github.event.issue.title }}."
